<a href="https://colab.research.google.com/github/thatajml/Student-Performance-Prediction/blob/dataset/Copy_1_of_ml_proj.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

# Replace 'path/to/your/file' with the actual path to your CSV file in Google Drive
file_path = '/content/drive/MyDrive/student-scores.csv'

try:
    df = pd.read_csv(file_path)
    print("CSV file read successfully.")
    display(df.head(10))
except FileNotFoundError:
    print(f"Error: The file was not found at {file_path}")
except Exception as e:
    print(f"An error occurred: {e}")

CSV file read successfully.

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
4,5,Anthony,Campos,anthony.campos.5@gslingacademy.com,male,False,5,False,10,Unknown,84,77,65,65,80,74,76
5,6,Kelly,Wade,kelly.wade.6@gslingacademy.com,female,False,2,False,26,Unknown,93,100,67,78,72,80,84
6,7,Anthony,Smith,anthony.smith.7@gslingacademy.com,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64
7,8,George,Short,george.short.8@gslingacademy.com,male,True,2,True,34,Software Engineer,95,95,82,63,84,70,85
8,9,Stanley,Gutierrez,stanley.gutierrez.9@gslingacademy.com,male,False,6,False,25,Unknown,94,68,94,85,81,74,72
9,10,Audrey,Simpson,audrey.simpson.10@gslingacademy.com,female,False,3,True,18,Teacher,98,69,88,71,67,71,73

In [ ]:
df.isnull().sum()

id                            0
first_name                    0
last_name                     0
email                         0
gender                        0
part_time_job                 0
absence_days                  0
extracurricular_activities    0
weekly_self_study_hours       0
career_aspiration             0
math_score                    0
history_score                 0
physics_score                 0
chemistry_score               0
biology_score                 0
english_score                 0
geography_score               0
dtype: int64

In [3]:
print(df.shape)

(2000, 17)

In [ ]:
unique_career_aspirations = df['career_aspiration'].unique()
print("Unique values in 'career_aspiration' column:")
display(unique_career_aspirations)

Unique values in 'career_aspiration' column:

array(['Lawyer', 'Doctor', 'Government Officer', 'Artist', 'Unknown',
       'Software Engineer', 'Teacher', 'Business Owner', 'Scientist',
       'Banker', 'Writer', 'Accountant', 'Designer',
       'Construction Engineer', 'Game Developer', 'Stock Investor',
       'Real Estate Developer'], dtype=object)

In [4]:
unknown_aspirations_count = df[df['career_aspiration'] == 'Unknown'].shape[0]
print(f"Number of tuples with 'career_aspiration' as 'Unknown': {unknown_aspirations_count}")

Number of tuples with 'career_aspiration' as 'Unknown': 223

In [5]:
df1 = df[df['career_aspiration'] != 'Unknown'].copy()
print("New DataFrame df1 created with 'Unknown' career aspirations removed.")
display(df1.head(10))

New DataFrame df1 created with 'Unknown' career aspirations removed.

,id,first_name,last_name,email,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,1,Paul,Casey,paul.casey.1@gslingacademy.com,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,2,Danielle,Sandoval,danielle.sandoval.2@gslingacademy.com,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,3,Tina,Andrews,tina.andrews.3@gslingacademy.com,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,4,Tara,Clark,tara.clark.4@gslingacademy.com,female,False,5,False,3,Artist,71,74,88,80,89,63,86
6,7,Anthony,Smith,anthony.smith.7@gslingacademy.com,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64
7,8,George,Short,george.short.8@gslingacademy.com,male,True,2,True,34,Software Engineer,95,95,82,63,84,70,85
9,10,Audrey,Simpson,audrey.simpson.10@gslingacademy.com,female,False,3,True,18,Teacher,98,69,88,71,67,71,73
10,11,Gabrielle,White,gabrielle.white.11@gslingacademy.com,female,False,2,False,7,Teacher,65,60,97,94,71,81,66
12,13,Patricia,Gomez,patricia.gomez.13@gslingacademy.com,female,True,7,False,4,Business Owner,94,59,69,67,89,65,73
13,14,Pamela,Jackson,pamela.jackson.14@gslingacademy.com,female,False,10,False,2,Business Owner,66,94,86,100,57,90,63

In [ ]:
print(df1.columns)

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'part_time_job',
       'absence_days', 'extracurricular_activities', 'weekly_self_study_hours',
       'career_aspiration', 'math_score', 'history_score', 'physics_score',
       'chemistry_score', 'biology_score', 'english_score', 'geography_score'],
      dtype='object')

In [6]:
df1 = df1.drop(columns=["id", "first_name", "last_name", "email"])
print("Columns dropped successfully.")
display(df1.head())

Columns dropped successfully.

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86
6,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64

**Feature engineering**

In [7]:
job_subject_weights = {
    "Lawyer": {
        "math": 0.2, "history": 0.5, "physics": 0.1, "chemistry": 0.0,
        "biology": 0.0, "english": 0.7, "geography": 0.3
    },
    "Doctor": {
        "math": 0.2, "history": 0.1, "physics": 0.2, "chemistry": 0.7,
        "biology": 0.9, "english": 0.4, "geography": 0.2
    },
    "Government Officer": {
        "math": 0.3, "history": 0.7, "physics": 0.2, "chemistry": 0.2,
        "biology": 0.2, "english": 0.6, "geography": 0.6
    },
    "Artist": {
        "math": 0.1, "history": 0.2, "physics": 0.1, "chemistry": 0.0,
        "biology": 0.0, "english": 0.7, "geography": 0.2
    },
    "Software Engineer": {
        "math": 0.9, "history": 0.1, "physics": 0.6, "chemistry": 0.2,
        "biology": 0.0, "english": 0.3, "geography": 0.1
    },
    "Teacher": {
        "math": 0.4, "history": 0.4, "physics": 0.4, "chemistry": 0.4,
        "biology": 0.4, "english": 0.6, "geography": 0.4
    },
    "Business Owner": {
        "math": 0.5, "history": 0.3, "physics": 0.2, "chemistry": 0.1,
        "biology": 0.1, "english": 0.6, "geography": 0.3
    },
    "Scientist": {
        "math": 0.9, "history": 0.2, "physics": 0.8, "chemistry": 0.8,
        "biology": 0.7, "english": 0.3, "geography": 0.2
    },
    "Banker": {
        "math": 0.8, "history": 0.2, "physics": 0.3, "chemistry": 0.1,
        "biology": 0.0, "english": 0.5, "geography": 0.1
    },
    "Writer": {
        "math": 0.1, "history": 0.4, "physics": 0.1, "chemistry": 0.0,
        "biology": 0.0, "english": 0.9, "geography": 0.2
    },
    "Accountant": {
        "math": 0.9, "history": 0.2, "physics": 0.3, "chemistry": 0.1,
        "biology": 0.0, "english": 0.4, "geography": 0.1
    },
    "Designer": {
        "math": 0.3, "history": 0.2, "physics": 0.2, "chemistry": 0.0,
        "biology": 0.0, "english": 0.6, "geography": 0.3
    },
    "Construction Engineer": {
        "math": 0.8, "history": 0.2, "physics": 0.9, "chemistry": 0.6,
        "biology": 0.1, "english": 0.3, "geography": 0.4
    },
    "Game Developer": {
        "math": 0.9, "history": 0.1, "physics": 0.6, "chemistry": 0.2,
        "biology": 0.0, "english": 0.4, "geography": 0.1
    },
    "Stock Investor": {
        "math": 0.8, "history": 0.3, "physics": 0.2, "chemistry": 0.1,
        "biology": 0.0, "english": 0.5, "geography": 0.3
    },
    "Real Estate Developer": {
        "math": 0.6, "history": 0.3, "physics": 0.4, "chemistry": 0.2,
        "biology": 0.0, "english": 0.5, "geography": 0.6
    }
}

In [9]:
import pandas as pd

# job_subject_weights defined earlier

def compute_target_suitability(df, job_weights):
    subjects = ["math", "history", "physics", "chemistry", "biology", "english", "geography"]
    df["target_suitability"] = df.apply(
        lambda row: sum(
            row[f"{sub}_score"] * job_weights[row["career_aspiration"]][sub]
            for sub in subjects
        ),
        axis=1
    )
    return df

df1 = compute_target_suitability(df1, job_subject_weights)
df1.head(10)

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,target_suitability
0,male,False,3,False,27,Lawyer,73,81,93,97,63,80,87,146.5
1,female,False,2,False,47,Doctor,90,86,96,100,90,88,90,250.0
2,female,False,9,True,13,Government Officer,81,97,95,96,65,77,94,246.0
3,female,False,5,False,3,Artist,71,74,88,80,89,63,86,92.0
6,male,False,3,True,23,Software Engineer,99,96,97,73,88,76,64,200.7
7,male,True,2,True,34,Software Engineer,95,95,82,63,84,70,85,186.3
9,female,False,3,True,18,Teacher,98,69,88,71,67,71,73,229.0
10,female,False,2,False,7,Teacher,65,60,97,94,71,81,66,229.8
12,female,True,7,False,4,Business Owner,94,59,69,67,89,65,73,155.0
13,female,False,10,False,2,Business Owner,66,94,86,100,57,90,63,167.0

In [10]:
from sklearn.preprocessing import LabelEncoder

# Create a copy of df1
df2 = df1.copy()

# Apply Label Encoding to specified columns
columns_to_encode = ["gender", "extracurricular_activities", "part_time_job", "career_aspiration"]

for col in columns_to_encode:
    le = LabelEncoder()
    df2[col] = le.fit_transform(df2[col])

# Display the first few rows of the modified df2
display(df2.head())

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,career_aspiration,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,target_suitability
0,1,0,3,0,27,9,73,81,93,97,63,80,87,146.5
1,0,0,2,0,47,6,90,86,96,100,90,88,90,250.0
2,0,0,9,1,13,8,81,97,95,96,65,77,94,246.0
3,0,0,5,0,3,1,71,74,88,80,89,63,86,92.0
6,1,0,3,1,23,12,99,96,97,73,88,76,64,200.7

In [12]:
# Define features (X) and target (y)
features = [
    "gender",
    "part_time_job",
    "absence_days",
    "extracurricular_activities",
    "weekly_self_study_hours",
    "math_score",
    "history_score",
    "physics_score",
    "chemistry_score",
    "biology_score",
    "english_score",
    "geography_score",
    "career_aspiration" # Keeping career_aspiration as requested
]

X = df2[features]
y = df2["target_suitability"]

print("Features (X) and Target (y) separated successfully.")
display(X.head())
display(y.head())

Features (X) and Target (y) separated successfully.

,gender,part_time_job,absence_days,extracurricular_activities,weekly_self_study_hours,math_score,history_score,physics_score,chemistry_score,biology_score,english_score,geography_score,career_aspiration
0,1,0,3,0,27,73,81,93,97,63,80,87,9
1,0,0,2,0,47,90,86,96,100,90,88,90,6
2,0,0,9,1,13,81,97,95,96,65,77,94,8
3,0,0,5,0,3,71,74,88,80,89,63,86,1
6,1,0,3,1,23,99,96,97,73,88,76,64,12

0    146.5
1    250.0
2    246.0
3     92.0
6    200.7
Name: target_suitability, dtype: float64

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [14]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.pipeline import Pipeline

numeric_features = ["absence_days", "weekly_self_study_hours",
                    "math_score", "history_score", "physics_score",
                    "chemistry_score", "biology_score", "english_score", "geography_score"]

categorical_features = ["gender", "part_time_job", "extracurricular_activities", "career_aspiration"]

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numeric_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [17]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Example: Random Forest pipeline
regressor = Pipeline(steps=[
    ("preprocessor", preprocessor),
    ("model", RandomForestRegressor(n_estimators=100, random_state=42))
])

regressor.fit(X_train, y_train)

# Evaluation
y_pred = regressor.predict(X_test)
print("RMSE:", mean_squared_error(y_test, y_pred))
print("R²:", r2_score(y_test, y_pred))

RMSE: 32.86801146910099
R²: 0.9837845845778126

In [18]:
print("Range of 'target_suitability':")
print("Minimum:", df1['target_suitability'].min())
print("Maximum:", df1['target_suitability'].max())

Range of 'target_suitability':
Minimum: 86.1
Maximum: 373.4

# checking with a dummy tuple

In [22]:
sample_student = {
    "gender": "Male",                     # categorical
    "part_time_job": 1,                   # 1 = has job
    "absence_days": 5,                    # few absences
    "extracurricular_activities": 1,      # participates
    "weekly_self_study_hours": 12,        # good self-study
    "career_aspiration": "Software Engineer",  # chosen career
    "math_score": 88,
    "history_score": 65,
    "physics_score": 92,
    "chemistry_score": 85,
    "biology_score": 70,
    "english_score": 78,
    "geography_score": 60
}

In [23]:
# Convert to DataFrame for sklearn pipeline
sample_df = pd.DataFrame([sample_student])

predicted_score = regressor.predict(sample_df)[0]
print("Predicted suitability score:", predicted_score)

Predicted suitability score: 170.89199999999997

In [25]:
# Calculate the maximum possible target suitability score for the predicted career
career = sample_student["career_aspiration"]
max_possible_score = sum(100 * weight for weight in job_subject_weights[career].values())

# Convert the predicted score to a percentage
predicted_percentage = (predicted_score / max_possible_score) * 100

print(f"Predicted suitability score as a percentage: {predicted_percentage:.2f}%")

Predicted suitability score as a percentage: 77.68%